# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export BUN_INSTALL="$HOME/.bun";
export CARGO_INSTALL="$HOME/.cargo"
export PATH="$BUN_INSTALL/bin:$CARGO_INSTALL/bin:$PATH"

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
    for rc in ~/.bashrc.d/*; do
        if [ -f "$rc" ]; then
            . "$rc"
        fi
    done
fi
unset rc

# ---------- shortcut start ----------
# This code was auto-generated by `$ shortcut setup`.
# See `$ shortcut -- help` for more info.
function s() {
    if [[ "$1" = "-a" ]]; then
        shortcut add "$2" "$3"
    elif [[ "$1" = "-r" ]]; then
        shortcut remove "$2"
    elif [[ "$1" = "-l" ]]; then
        shortcut list
    elif [[ "$1" = "-b" ]]; then
        popd
    else
        pushd $(shortcut get "$1")
    fi
}
# ---------- shortcut end ----------

alias tn='tmux new-session "nvim ."'
export EDITOR=nvim
